package com.noomit.backend.shared.error;

public enum ErrorCode {
    INVALID_REQUEST,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_INVALID_CREDENTIALS,
    ADMIN_MEMBER_NOT_FOUND,
    ADMIN_ROLE_INVALID,
    ADMIN_SELF_DEMOTION,
    RECEPTION_INVALID_REQUEST,
    RECEPTION_NOT_FOUND,
    RECEPTION_SLOT_NOT_OWNED,
    RECEPTION_INVALID_STATUS,
    RECEPTION_ALREADY_CANCELLED,
    RECEPTION_CONCURRENT_MODIFICATION,
    RECEPTION_SLOT_ALREADY_BOOKED,
    REPAIR_CASE_NOT_FOUND,
    REPAIR_CASE_ACCESS_DENIED,
    REPAIR_CASE_INVALID_STATUS,
    REPAIR_DETAIL_NOT_FOUND,
    REPAIR_DETAIL_NOT_IN_CASE,
    CUSTOMER_PHONE_ALREADY_EXISTS,
    CUSTOMER_NOT_FOUND,
    PRODUCT_SUB_CATEGORY_NOT_FOUND,
    PRODUCT_MODEL_CODE_ALREADY_EXISTS
}
