package com.noomit.backend.shared.error;

public enum ErrorCode {
    INVALID_REQUEST,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_INVALID_CREDENTIALS,
    ADMIN_MEMBER_NOT_FOUND,
    ADMIN_ROLE_INVALID,
    ADMIN_SELF_DEMOTION,
    RECEPTION_INVALID_REQUEST,
    RECEPTION_INVALID_STATUS,
    RECEPTION_ALREADY_CANCELLED,
    REPAIR_CASE_NOT_FOUND,
    CUSTOMER_PHONE_ALREADY_EXISTS,
    CUSTOMER_NOT_FOUND
}
